// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWlR48L64AKN3GPMQei1s9PsDXfhP4_o',
    appId: '1:338204786428:web:9b82adf032142d05182179',
    messagingSenderId: '338204786428',
    projectId: 'lifetalk-ae825',
    authDomain: 'lifetalk-ae825.firebaseapp.com',
    storageBucket: 'lifetalk-ae825.firebasestorage.app',
    measurementId: 'G-295TFN91K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwwAt4ZYyLxtxXQFmxve7JEZOgB6tPQU',
    appId: '1:338204786428:android:fb9dc328d79a005b182179',
    messagingSenderId: '338204786428',
    projectId: 'lifetalk-ae825',
    storageBucket: 'lifetalk-ae825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-1DKpjgRul8ZjbULP3R2bHHMqyuDGsVA',
    appId: '1:338204786428:ios:545795a413392282182179',
    messagingSenderId: '338204786428',
    projectId: 'lifetalk-ae825',
    storageBucket: 'lifetalk-ae825.firebasestorage.app',
    iosBundleId: 'com.example.lifetalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-1DKpjgRul8ZjbULP3R2bHHMqyuDGsVA',
    appId: '1:338204786428:ios:545795a413392282182179',
    messagingSenderId: '338204786428',
    projectId: 'lifetalk-ae825',
    storageBucket: 'lifetalk-ae825.firebasestorage.app',
    iosBundleId: 'com.example.lifetalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWlR48L64AKN3GPMQei1s9PsDXfhP4_o',
    appId: '1:338204786428:web:4df439e64318e5dd182179',
    messagingSenderId: '338204786428',
    projectId: 'lifetalk-ae825',
    authDomain: 'lifetalk-ae825.firebaseapp.com',
    storageBucket: 'lifetalk-ae825.firebasestorage.app',
    measurementId: 'G-DT9F1FRKZK',
  );

}